### PR TITLE
Add Carlito fonts

### LINKED ISSUE #1441: Add Carlito and Caladea
https://github.com/huertatipografica/Caladea

Carlito has no github, to date

### PR DESCRIPTION
**Pull request by ronaldtse**
Fixes google/fonts#1441.

cc: @davelab6, @mfwitten

### CODE REVIEW

**Comment by ronaldtse** [comment]
@davelab6, @mfwitten this PR should be ready for merging, feel free to provide feedback if any changes are necessary. Thanks!

**Comment by ronaldtse** [comment]
Pinging @davelab6, @mfwitten for a merge. Thanks!

**Comment by rdrpenguin04** [comment]
I'm hoping for this to get finalized too, and it's been... how long? Could this be merged, or could a reason be given for why it hasn't been? Thanks!

**Comment by ronaldtse** [comment]
Thanks @rdrpenguin04 , perhaps we can try pinging the Google Fonts team: @anthrotype @m4rc1e @marekjez86 @simoncozens ...?

**Comment by davelab6** [comment]
Looks good, thanks!

**Comment by ronaldtse** [comment]
Thank you very much @davelab6 !

**Pull request merged**
